// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "mfu/AlgorithmApi.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/TServerSocket.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::fusion_api;

class AlgorithmApiHandler : virtual public AlgorithmApiIf {
 public:
  AlgorithmApiHandler() {
    // Your initialization goes here
  }

  void multiDeviceFusion(const std::map<std::string, std::vector<CameraTarget> > & cml, const std::map<std::string, std::vector<RadarTarget> > & rml, const std::map<std::string, std::vector<LidarTarget> > & lml) {
    // Your implementation goes here
    printf("multiDeviceFusion\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<AlgorithmApiHandler> handler(new AlgorithmApiHandler());
  ::std::shared_ptr<TProcessor> processor(new AlgorithmApiProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

